name: Build and deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create archive
        run: |
          mkdir -p build/archive
          tar -czf build/archive/artifact.tar.gz ./build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload existing artifact.tar.gz file
          name: artifact
          path: './build/archive/artifact.tar.gz'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          # GitHub Pages configuration
          github_token: ${{ secrets.GITHUB_TOKEN }}
          folder: './build'